# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image: lgonzalez/wclanding

pipelines:
  branches:
    develop:
      - step:
          name: Building
          caches:
          - node
          script: # Modify the commands below to build your repository.
          - npm install
          - npm run build:dev
          artifacts:
          - dist/**
      - step:
          name: Deploying
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.8
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'us-east-2'
                S3_BUCKET: 'whitecloud-aws'
                LOCAL_PATH: 'dist'
                DELET_FLAG: 'true'
    master:
      - step:
          name: Building
          caches:
          - node
          script: # Modify the commands below to build your repository.
          - npm install
          - npm run build:prod
          artifacts:
          - dist/**
      - step:
          name: Deploying
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.8
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'us-east-2'
                S3_BUCKET: 'whitecloud-aws'
                LOCAL_PATH: 'dist'
                DELET_FLAG: 'true'